feat: add ECR login, tagging, and pushing steps to CI/CD pipeline

diff --git a/.github/workflows/delpho-release.yaml b/.github/workflows/delpho-release.yaml
--- a/.github/workflows/delpho-release.yaml
+++ b/.github/workflows/delpho-release.yaml
@@ -71,6 +71,38 @@ jobs:
             role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
             aws-region: ${{ secrets.AWS_REGION }}
 
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Tag and Push to ECR
+        env:
+            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+            TAG: ${{ needs.env-setup.outputs.image_tag }}
+        run: |
+            docker tag openzeppeline-relayer-local:${{ github.sha }} $REGISTRY/${{ env.ECR_REPOSITORY_APP }}:$TAG
+            docker tag openzeppeline-relayer-local:${{ github.sha }} $REGISTRY/${{ env.ECR_REPOSITORY_APP }}:latest
+            docker push $REGISTRY/${{ env.ECR_REPOSITORY_APP }}:$TAG
+            docker push $REGISTRY/${{ env.ECR_REPOSITORY_APP }}:latest
+
+  deploy-to-ecs:
+    needs: [env-setup, build-and-upload-image]
+    runs-on: ubuntu-latest
+    environment: ${{ needs.env-setup.outputs.target_env }}
+    steps:
+
+      - name: Checkout code
+        uses: actions/checkout@v6
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
+            aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
       - name: Generate config file
         id: generate-config
         env:
@@ -88,16 +120,89 @@ jobs:
           sed -i "s|HYPER_EVM_RPC_URL_2|$HYPER_EVM_RPC_URL_2|g" ${APP_DIR}/config/config.json
           echo "PAYLOAD=$(jq -c . ${APP_DIR}/config/config.json)" >> $GITHUB_OUTPUT
 
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
 
-      - name: Tag and Push to ECR
-        env:
-            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-            TAG: ${{ needs.env-setup.outputs.image_tag }}
+      - name: Upload to EFS via Lambda
         run: |
-            docker tag openzeppeline-relayer:${{ github.sha }} $REGISTRY/${{ env.ECR_REPOSITORY_APP }}:$TAG
-            docker tag openzeppeline-relayer:${{ github.sha }} $REGISTRY/${{ env.ECR_REPOSITORY_APP }}:latest
-            docker push $REGISTRY/${{ env.ECR_REPOSITORY_APP }}:$TAG
-            docker push $REGISTRY/${{ env.ECR_REPOSITORY_APP }}:latest
+          aws lambda invoke \
+            --function-name ${LAMBDA_FUNCTION_NAME} \
+            --cli-binary-format raw-in-base64-out \
+            --payload '${{ steps.generate-config.outputs.PAYLOAD }}' \
+            response.json
+
+          echo "Response:"
+          cat response.json
+
+          # Check response
+          if grep -q '"statusCode": 200' response.json; then
+            echo "✅ Config uploaded successfully to EFS"
+          else
+            echo "❌ Upload failed"
+            cat response.json
+            exit 1
+          fi
+
+      - name: Upload networks folder files to EFS via Lambda
+        run: |
+          NETWORKS_DIR="${APP_DIR}/config/networks"
+
+          ls -al "$NETWORKS_DIR"
+
+          if [ -d "$NETWORKS_DIR" ] && [ "$(ls -A "$NETWORKS_DIR")" ]; then
+            for file in "$NETWORKS_DIR"/*; do
+              filename=$(basename "$file")
+              filepath="networks/$filename"
+
+              echo "📤 Uploading $filepath"
+
+              # Read file content safely
+              content=$(cat "$file")
+
+              # Wrap into a JSON payload
+              PAYLOAD=$(jq -n \
+                --arg filename "$filepath" \
+                --argjson payload "$content" \
+                '{filename: $filename, payload: $payload}')
+
+              aws lambda invoke \
+                --function-name ${LAMBDA_FUNCTION_NAME} \
+                --cli-binary-format raw-in-base64-out \
+                --payload "$PAYLOAD" \
+                response.json
+
+              echo "Response for $filepath:"
+              cat response.json
+
+              if grep -q '"statusCode": 200' response.json; then
+                echo "✅ $filepath uploaded successfully to EFS"
+              else
+                echo "❌ Upload failed for $filepath"
+                cat response.json
+                exit 1
+              fi
+            done
+          else
+            echo "⚠️ No files found in $NETWORKS_DIR, skipping upload."
+          fi
+
+    #   - name: Download task definition
+    #     run: |
+    #         aws ecs describe-task-definition \
+    #         --task-definition ${{ env.ECS_TASK_DEFINITION_FAMILY }} \
+    #         --query taskDefinition \
+    #         > task-definition.json
+
+    #   - name: Fill in the new image ID in the Amazon ECS task definition
+    #     id: task-def
+    #     uses: aws-actions/amazon-ecs-render-task-definition@v1
+    #     with:
+    #       task-definition: task-definition.json
+    #       container-name: ${{ env.CONTAINER_NAME }}
+    #       image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_APP }}:}}:${{ needs.env-setup.outputs.image_tag }}
+
+    #   - name: Deploy Amazon ECS task definition
+    #     uses: aws-actions/amazon-ecs-deploy-task-definition@v2
+    #     with:
+    #       task-definition: ${{ steps.task-def.outputs.task-definition }}
+    #       service: ${{ env.ECS_SERVICE }}
+    #       cluster: ${{ env.ECS_CLUSTER }}
+    #       # wait-for-service-stability: true
